/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.24 at 02:22:49 PM CEST 
//

package org.imsglobal.xsd.imsmd_v1p2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for structureType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="structureType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsmd_v1p2}source"/>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsmd_v1p2}value"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "structureType", propOrder = {"source", "value"})
public class StructureType
{

	@XmlElement(required = true)
	private SourceType source;
	@XmlElement(required = true)
	private ValueType value;

	/**
	 * Gets the value of the source property.
	 * @return
	 *         possible object is {@link SourceType }
	 */
	public SourceType getSource()
	{
		return source;
	}

	/**
	 * Sets the value of the source property.
	 * @param value
	 *           allowed object is {@link SourceType }
	 */
	public void setSource(SourceType value)
	{
		source = value;
	}

	/**
	 * Gets the value of the value property.
	 * @return
	 *         possible object is {@link ValueType }
	 */
	public ValueType getValue()
	{
		return value;
	}

	/**
	 * Sets the value of the value property.
	 * @param value
	 *           allowed object is {@link ValueType }
	 */
	public void setValue(ValueType value)
	{
		this.value = value;
	}

}
