//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.24 at 04:39:25 PM CEST 
//

package org.openarchives.oai._2;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * A header has a unique identifier, a datestamp,
 * and setSpec(s) in case the item from which
 * the record is disseminated belongs to set(s).
 * the header can carry a deleted status indicating
 * that the record is deleted.
 * <p>
 * Java class for headerType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="headerType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="identifier" type="{http://www.openarchives.org/OAI/2.0/}identifierType"/>
 *         &lt;element name="datestamp" type="{http://www.openarchives.org/OAI/2.0/}UTCdatetimeType"/>
 *         &lt;element name="setSpec" type="{http://www.openarchives.org/OAI/2.0/}setSpecType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="status" type="{http://www.openarchives.org/OAI/2.0/}statusType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "headerType", propOrder = {"identifier", "datestamp", "setSpec"})
public class HeaderType implements Serializable
{

	/**
	 * 
	 */
	private static final long serialVersionUID = 7580203383344336956L;
	@XmlElement(required = true)
	protected String identifier;
	@XmlElement(required = true)
	protected String datestamp;
	protected List<String> setSpec;
	@XmlAttribute
	protected StatusType status;

	/**
	 * Gets the value of the identifier property.
	 * @return
	 *         possible object is {@link String }
	 */
	public String getIdentifier()
	{
		return identifier;
	}

	/**
	 * Sets the value of the identifier property.
	 * @param value
	 *           allowed object is {@link String }
	 */
	public void setIdentifier(String value)
	{
		identifier = value;
	}

	/**
	 * Gets the value of the datestamp property.
	 * @return
	 *         possible object is {@link String }
	 */
	public String getDatestamp()
	{
		return datestamp;
	}

	/**
	 * Sets the value of the datestamp property.
	 * @param value
	 *           allowed object is {@link String }
	 */
	public void setDatestamp(String value)
	{
		datestamp = value;
	}

	/**
	 * Gets the value of the setSpec property.
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
	 * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the setSpec property.
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getSetSpec().add(newItem);
	 * </pre>
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 */
	public List<String> getSetSpec()
	{
		if (setSpec == null)
		{
			setSpec = new ArrayList<String>();
		}
		return setSpec;
	}

	/**
	 * Gets the value of the status property.
	 * @return
	 *         possible object is {@link StatusType }
	 */
	public StatusType getStatus()
	{
		return status;
	}

	/**
	 * Sets the value of the status property.
	 * @param value
	 *           allowed object is {@link StatusType }
	 */
	public void setStatus(StatusType value)
	{
		status = value;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode()
	{
		final int prime = 31;
		int result = 1;
		result = prime * result + ((datestamp == null) ? 0 : datestamp.hashCode());
		result = prime * result + ((identifier == null) ? 0 : identifier.hashCode());
		result = prime * result + ((setSpec == null) ? 0 : setSpec.hashCode());
		result = prime * result + ((status == null) ? 0 : status.hashCode());
		return result;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj)
	{
		if (this == obj)
		{
			return true;
		}
		if (obj == null)
		{
			return false;
		}
		if (getClass() != obj.getClass())
		{
			return false;
		}
		HeaderType other = (HeaderType) obj;
		if (datestamp == null)
		{
			if (other.datestamp != null)
			{
				return false;
			}
		}
		else if (!datestamp.equals(other.datestamp))
		{
			return false;
		}
		if (identifier == null)
		{
			if (other.identifier != null)
			{
				return false;
			}
		}
		else if (!identifier.equals(other.identifier))
		{
			return false;
		}
		if (setSpec == null)
		{
			if (other.setSpec != null)
			{
				return false;
			}
		}
		else if (!setSpec.equals(other.setSpec))
		{
			return false;
		}
		if (status != other.status)
		{
			return false;
		}
		return true;
	}
}
