//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.24 at 04:39:25 PM CEST 
//

package org.openarchives.oai._2;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ListSetsType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ListSetsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="set" type="{http://www.openarchives.org/OAI/2.0/}setType" maxOccurs="unbounded"/>
 *         &lt;element name="resumptionToken" type="{http://www.openarchives.org/OAI/2.0/}resumptionTokenType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ListSetsType", propOrder = {"set", "resumptionToken"})
public class ListSetsType implements Serializable
{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1087417096270798964L;
	@XmlElement(required = true)
	protected List<SetType> set;
	protected ResumptionTokenType resumptionToken;

	/**
	 * Gets the value of the set property.
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
	 * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the set property.
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getSet().add(newItem);
	 * </pre>
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link SetType }
	 */
	public List<SetType> getSet()
	{
		if (set == null)
		{
			set = new ArrayList<SetType>();
		}
		return set;
	}

	/**
	 * Gets the value of the resumptionToken property.
	 * @return
	 *         possible object is {@link ResumptionTokenType }
	 */
	public ResumptionTokenType getResumptionToken()
	{
		return resumptionToken;
	}

	/**
	 * Sets the value of the resumptionToken property.
	 * @param value
	 *           allowed object is {@link ResumptionTokenType }
	 */
	public void setResumptionToken(ResumptionTokenType value)
	{
		resumptionToken = value;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode()
	{
		final int prime = 31;
		int result = 1;
		result = prime * result + ((resumptionToken == null) ? 0 : resumptionToken.hashCode());
		result = prime * result + ((set == null) ? 0 : set.hashCode());
		return result;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj)
	{
		if (this == obj)
		{
			return true;
		}
		if (obj == null)
		{
			return false;
		}
		if (getClass() != obj.getClass())
		{
			return false;
		}
		ListSetsType other = (ListSetsType) obj;
		if (resumptionToken == null)
		{
			if (other.resumptionToken != null)
			{
				return false;
			}
		}
		else if (!resumptionToken.equals(other.resumptionToken))
		{
			return false;
		}
		if (set == null)
		{
			if (other.set != null)
			{
				return false;
			}
		}
		else if (!set.equals(other.set))
		{
			return false;
		}
		return true;
	}

}
