//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.24 at 04:39:25 PM CEST 
//

package org.openarchives.oai._2;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * A record has a header, a metadata part, and
 * an optional about container
 * <p>
 * Java class for recordType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="recordType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="header" type="{http://www.openarchives.org/OAI/2.0/}headerType"/>
 *         &lt;element name="metadata" type="{http://www.openarchives.org/OAI/2.0/}metadataType" minOccurs="0"/>
 *         &lt;element name="about" type="{http://www.openarchives.org/OAI/2.0/}aboutType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "recordType", propOrder = {"header", "metadata", "about"})
public class RecordType implements Serializable
{

	/**
	 * 
	 */
	private static final long serialVersionUID = 5334216893932200151L;
	@XmlElement(required = true)
	protected HeaderType header;
	protected MetadataType metadata;
	protected List<AboutType> about;

	/**
	 * Gets the value of the header property.
	 * @return
	 *         possible object is {@link HeaderType }
	 */
	public HeaderType getHeader()
	{
		return header;
	}

	/**
	 * Sets the value of the header property.
	 * @param value
	 *           allowed object is {@link HeaderType }
	 */
	public void setHeader(HeaderType value)
	{
		header = value;
	}

	/**
	 * Gets the value of the metadata property.
	 * @return
	 *         possible object is {@link MetadataType }
	 */
	public MetadataType getMetadata()
	{
		return metadata;
	}

	/**
	 * Sets the value of the metadata property.
	 * @param value
	 *           allowed object is {@link MetadataType }
	 */
	public void setMetadata(MetadataType value)
	{
		metadata = value;
	}

	/**
	 * Gets the value of the about property.
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
	 * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the about property.
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getAbout().add(newItem);
	 * </pre>
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link AboutType }
	 */
	public List<AboutType> getAbout()
	{
		if (about == null)
		{
			about = new ArrayList<AboutType>();
		}
		return about;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode()
	{
		final int prime = 31;
		int result = 1;
		result = prime * result + ((about == null) ? 0 : about.hashCode());
		result = prime * result + ((header == null) ? 0 : header.hashCode());
		result = prime * result + ((metadata == null) ? 0 : metadata.hashCode());
		return result;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj)
	{
		if (this == obj)
		{
			return true;
		}
		if (obj == null)
		{
			return false;
		}
		if (getClass() != obj.getClass())
		{
			return false;
		}
		RecordType other = (RecordType) obj;
		if (about == null)
		{
			if (other.about != null)
			{
				return false;
			}
		}
		else if (!about.equals(other.about))
		{
			return false;
		}
		if (header == null)
		{
			if (other.header != null)
			{
				return false;
			}
		}
		else if (!header.equals(other.header))
		{
			return false;
		}
		if (metadata == null)
		{
			if (other.metadata != null)
			{
				return false;
			}
		}
		else if (!metadata.equals(other.metadata))
		{
			return false;
		}
		return true;
	}

}
