//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.24 at 04:39:25 PM CEST 
//

package org.openarchives.oai._2;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * Define requestType, indicating the protocol request that
 * led to the response. Element content is BASE-URL, attributes are arguments
 * of protocol request, attribute-values are values of arguments of protocol
 * request
 * <p>
 * Java class for requestType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="requestType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>anyURI">
 *       &lt;attribute name="verb" type="{http://www.openarchives.org/OAI/2.0/}verbType" />
 *       &lt;attribute name="identifier" type="{http://www.openarchives.org/OAI/2.0/}identifierType" />
 *       &lt;attribute name="metadataPrefix" type="{http://www.openarchives.org/OAI/2.0/}metadataPrefixType" />
 *       &lt;attribute name="from" type="{http://www.openarchives.org/OAI/2.0/}UTCdatetimeType" />
 *       &lt;attribute name="until" type="{http://www.openarchives.org/OAI/2.0/}UTCdatetimeType" />
 *       &lt;attribute name="set" type="{http://www.openarchives.org/OAI/2.0/}setSpecType" />
 *       &lt;attribute name="resumptionToken" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "requestType", propOrder = {"value"})
public class RequestType implements Serializable
{

	/**
	 * 
	 */
	private static final long serialVersionUID = -2848136159099725424L;
	@XmlValue
	@XmlSchemaType(name = "anyURI")
	protected String value;
	@XmlAttribute
	protected VerbType verb;
	@XmlAttribute
	protected String identifier;
	@XmlAttribute
	protected String metadataPrefix;
	@XmlAttribute
	protected String from;
	@XmlAttribute
	protected String until;
	@XmlAttribute
	protected String set;
	@XmlAttribute
	protected String resumptionToken;

	/**
	 * Gets the value of the value property.
	 * @return
	 *         possible object is {@link String }
	 */
	public String getValue()
	{
		return value;
	}

	/**
	 * Sets the value of the value property.
	 * @param value
	 *           allowed object is {@link String }
	 */
	public void setValue(String value)
	{
		this.value = value;
	}

	/**
	 * Gets the value of the verb property.
	 * @return
	 *         possible object is {@link VerbType }
	 */
	public VerbType getVerb()
	{
		return verb;
	}

	/**
	 * Sets the value of the verb property.
	 * @param value
	 *           allowed object is {@link VerbType }
	 */
	public void setVerb(VerbType value)
	{
		verb = value;
	}

	/**
	 * Gets the value of the identifier property.
	 * @return
	 *         possible object is {@link String }
	 */
	public String getIdentifier()
	{
		return identifier;
	}

	/**
	 * Sets the value of the identifier property.
	 * @param value
	 *           allowed object is {@link String }
	 */
	public void setIdentifier(String value)
	{
		identifier = value;
	}

	/**
	 * Gets the value of the metadataPrefix property.
	 * @return
	 *         possible object is {@link String }
	 */
	public String getMetadataPrefix()
	{
		return metadataPrefix;
	}

	/**
	 * Sets the value of the metadataPrefix property.
	 * @param value
	 *           allowed object is {@link String }
	 */
	public void setMetadataPrefix(String value)
	{
		metadataPrefix = value;
	}

	/**
	 * Gets the value of the from property.
	 * @return
	 *         possible object is {@link String }
	 */
	public String getFrom()
	{
		return from;
	}

	/**
	 * Sets the value of the from property.
	 * @param value
	 *           allowed object is {@link String }
	 */
	public void setFrom(String value)
	{
		from = value;
	}

	/**
	 * Gets the value of the until property.
	 * @return
	 *         possible object is {@link String }
	 */
	public String getUntil()
	{
		return until;
	}

	/**
	 * Sets the value of the until property.
	 * @param value
	 *           allowed object is {@link String }
	 */
	public void setUntil(String value)
	{
		until = value;
	}

	/**
	 * Gets the value of the set property.
	 * @return
	 *         possible object is {@link String }
	 */
	public String getSet()
	{
		return set;
	}

	/**
	 * Sets the value of the set property.
	 * @param value
	 *           allowed object is {@link String }
	 */
	public void setSet(String value)
	{
		set = value;
	}

	/**
	 * Gets the value of the resumptionToken property.
	 * @return
	 *         possible object is {@link String }
	 */
	public String getResumptionToken()
	{
		return resumptionToken;
	}

	/**
	 * Sets the value of the resumptionToken property.
	 * @param value
	 *           allowed object is {@link String }
	 */
	public void setResumptionToken(String value)
	{
		resumptionToken = value;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode()
	{
		final int prime = 31;
		int result = 1;
		result = prime * result + ((from == null) ? 0 : from.hashCode());
		result = prime * result + ((identifier == null) ? 0 : identifier.hashCode());
		result = prime * result + ((metadataPrefix == null) ? 0 : metadataPrefix.hashCode());
		result = prime * result + ((resumptionToken == null) ? 0 : resumptionToken.hashCode());
		result = prime * result + ((set == null) ? 0 : set.hashCode());
		result = prime * result + ((until == null) ? 0 : until.hashCode());
		result = prime * result + ((value == null) ? 0 : value.hashCode());
		result = prime * result + ((verb == null) ? 0 : verb.hashCode());
		return result;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj)
	{
		if (this == obj)
		{
			return true;
		}
		if (obj == null)
		{
			return false;
		}
		if (getClass() != obj.getClass())
		{
			return false;
		}
		RequestType other = (RequestType) obj;
		if (from == null)
		{
			if (other.from != null)
			{
				return false;
			}
		}
		else if (!from.equals(other.from))
		{
			return false;
		}
		if (identifier == null)
		{
			if (other.identifier != null)
			{
				return false;
			}
		}
		else if (!identifier.equals(other.identifier))
		{
			return false;
		}
		if (metadataPrefix == null)
		{
			if (other.metadataPrefix != null)
			{
				return false;
			}
		}
		else if (!metadataPrefix.equals(other.metadataPrefix))
		{
			return false;
		}
		if (resumptionToken == null)
		{
			if (other.resumptionToken != null)
			{
				return false;
			}
		}
		else if (!resumptionToken.equals(other.resumptionToken))
		{
			return false;
		}
		if (set == null)
		{
			if (other.set != null)
			{
				return false;
			}
		}
		else if (!set.equals(other.set))
		{
			return false;
		}
		if (until == null)
		{
			if (other.until != null)
			{
				return false;
			}
		}
		else if (!until.equals(other.until))
		{
			return false;
		}
		if (value == null)
		{
			if (other.value != null)
			{
				return false;
			}
		}
		else if (!value.equals(other.value))
		{
			return false;
		}
		if (verb != other.verb)
		{
			return false;
		}
		return true;
	}

}
