//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.24 at 04:39:25 PM CEST 
//

package org.openarchives.oai._2;

import java.io.Serializable;
import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * A resumptionToken may have 3 optional attributes
 * and can be used in ListSets, ListIdentifiers, ListRecords
 * responses.
 * <p>
 * Java class for resumptionTokenType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="resumptionTokenType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="expirationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="completeListSize" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *       &lt;attribute name="cursor" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "resumptionTokenType", propOrder = {"value"})
public class ResumptionTokenType implements Serializable
{

	/**
	 * 
	 */
	private static final long serialVersionUID = 2970015921400926163L;
	@XmlValue
	protected String value;
	@XmlAttribute
	@XmlSchemaType(name = "dateTime")
	protected XMLGregorianCalendar expirationDate;
	@XmlAttribute
	@XmlSchemaType(name = "positiveInteger")
	protected BigInteger completeListSize;
	@XmlAttribute
	@XmlSchemaType(name = "nonNegativeInteger")
	protected BigInteger cursor;

	/**
	 * Gets the value of the value property.
	 * @return
	 *         possible object is {@link String }
	 */
	public String getValue()
	{
		return value;
	}

	/**
	 * Sets the value of the value property.
	 * @param value
	 *           allowed object is {@link String }
	 */
	public void setValue(String value)
	{
		this.value = value;
	}

	/**
	 * Gets the value of the expirationDate property.
	 * @return
	 *         possible object is {@link XMLGregorianCalendar }
	 */
	public XMLGregorianCalendar getExpirationDate()
	{
		return expirationDate;
	}

	/**
	 * Sets the value of the expirationDate property.
	 * @param value
	 *           allowed object is {@link XMLGregorianCalendar }
	 */
	public void setExpirationDate(XMLGregorianCalendar value)
	{
		expirationDate = value;
	}

	/**
	 * Gets the value of the completeListSize property.
	 * @return
	 *         possible object is {@link BigInteger }
	 */
	public BigInteger getCompleteListSize()
	{
		return completeListSize;
	}

	/**
	 * Sets the value of the completeListSize property.
	 * @param value
	 *           allowed object is {@link BigInteger }
	 */
	public void setCompleteListSize(BigInteger value)
	{
		completeListSize = value;
	}

	/**
	 * Gets the value of the cursor property.
	 * @return
	 *         possible object is {@link BigInteger }
	 */
	public BigInteger getCursor()
	{
		return cursor;
	}

	/**
	 * Sets the value of the cursor property.
	 * @param value
	 *           allowed object is {@link BigInteger }
	 */
	public void setCursor(BigInteger value)
	{
		cursor = value;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode()
	{
		final int prime = 31;
		int result = 1;
		result = prime * result + ((completeListSize == null) ? 0 : completeListSize.hashCode());
		result = prime * result + ((cursor == null) ? 0 : cursor.hashCode());
		result = prime * result + ((expirationDate == null) ? 0 : expirationDate.hashCode());
		result = prime * result + ((value == null) ? 0 : value.hashCode());
		return result;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj)
	{
		if (this == obj)
		{
			return true;
		}
		if (obj == null)
		{
			return false;
		}
		if (getClass() != obj.getClass())
		{
			return false;
		}
		ResumptionTokenType other = (ResumptionTokenType) obj;
		if (completeListSize == null)
		{
			if (other.completeListSize != null)
			{
				return false;
			}
		}
		else if (!completeListSize.equals(other.completeListSize))
		{
			return false;
		}
		if (cursor == null)
		{
			if (other.cursor != null)
			{
				return false;
			}
		}
		else if (!cursor.equals(other.cursor))
		{
			return false;
		}
		if (expirationDate == null)
		{
			if (other.expirationDate != null)
			{
				return false;
			}
		}
		else if (!expirationDate.equals(other.expirationDate))
		{
			return false;
		}
		if (value == null)
		{
			if (other.value != null)
			{
				return false;
			}
		}
		else if (!value.equals(other.value))
		{
			return false;
		}
		return true;
	}

}
