//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.24 at 04:39:25 PM CEST 
//

package org.openarchives.oai._2;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for setType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="setType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="setSpec" type="{http://www.openarchives.org/OAI/2.0/}setSpecType"/>
 *         &lt;element name="setName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="setDescription" type="{http://www.openarchives.org/OAI/2.0/}descriptionType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "setType", propOrder = {"setSpec", "setName", "setDescription"})
public class SetType implements Serializable
{

	/**
	 * 
	 */
	private static final long serialVersionUID = -7038981641290523849L;
	@XmlElement(required = true)
	protected String setSpec;
	@XmlElement(required = true)
	protected String setName;
	protected List<DescriptionType> setDescription;

	/**
	 * Gets the value of the setSpec property.
	 * @return
	 *         possible object is {@link String }
	 */
	public String getSetSpec()
	{
		return setSpec;
	}

	/**
	 * Sets the value of the setSpec property.
	 * @param value
	 *           allowed object is {@link String }
	 */
	public void setSetSpec(String value)
	{
		setSpec = value;
	}

	/**
	 * Gets the value of the setName property.
	 * @return
	 *         possible object is {@link String }
	 */
	public String getSetName()
	{
		return setName;
	}

	/**
	 * Sets the value of the setName property.
	 * @param value
	 *           allowed object is {@link String }
	 */
	public void setSetName(String value)
	{
		setName = value;
	}

	/**
	 * Gets the value of the setDescription property.
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
	 * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the setDescription property.
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getSetDescription().add(newItem);
	 * </pre>
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link DescriptionType }
	 */
	public List<DescriptionType> getSetDescription()
	{
		if (setDescription == null)
		{
			setDescription = new ArrayList<DescriptionType>();
		}
		return setDescription;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode()
	{
		final int prime = 31;
		int result = 1;
		result = prime * result + ((setDescription == null) ? 0 : setDescription.hashCode());
		result = prime * result + ((setName == null) ? 0 : setName.hashCode());
		result = prime * result + ((setSpec == null) ? 0 : setSpec.hashCode());
		return result;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj)
	{
		if (this == obj)
		{
			return true;
		}
		if (obj == null)
		{
			return false;
		}
		if (getClass() != obj.getClass())
		{
			return false;
		}
		SetType other = (SetType) obj;
		if (setDescription == null)
		{
			if (other.setDescription != null)
			{
				return false;
			}
		}
		else if (!setDescription.equals(other.setDescription))
		{
			return false;
		}
		if (setName == null)
		{
			if (other.setName != null)
			{
				return false;
			}
		}
		else if (!setName.equals(other.setName))
		{
			return false;
		}
		if (setSpec == null)
		{
			if (other.setSpec != null)
			{
				return false;
			}
		}
		else if (!setSpec.equals(other.setSpec))
		{
			return false;
		}
		return true;
	}

}
